### ISSUE TITLE
Competion Bug Submission

### ISSUE THREAD

**Issue by KazutoKashima** [KazutoKashima/Project-Red-Alice-Rising#4]
Submit your bugs here!

*Use the following format*
```md
##### Bug Name  
## Description:  

## Traceback code (found in the terminal/CMD): 

## Image (If applicable):  
````

**Comment by KuromeiKashima** [comment]
Issues already found by devs before the event:
- #3 <- ICO file
- #2 <- PyGame.mixer error

**Comment by KazutoKashima** [comment]
Times up everyone! Any bugs submitted from this point won’t count!
